// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://terjjqqlsjfajcvbfyat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcmpqcXFsc2pmYWpjdmJmeWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4Mjk5MzIsImV4cCI6MjA3NzQwNTkzMn0._m42KHISsghgk5NYMM8mLv4UAFzVvilSNUqA5REjTac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});